FROM python:3.12-slim-bookworm


COPY requirements.txt .

RUN apt-get update -y && apt-get install -y wget gnupg
RUN apt-get install -y curl

RUN apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0  \
    libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3  \
    libxrandr2 libgbm1 libasound2 libatspi2.0-0 build-essential software-properties-common

RUN pip install --upgrade pip
RUN pip install -r requirements.txt --no-cache-dir
RUN playwright install --with-deps


COPY . .